
public enum GameEvent
{
    PATH_UPDATED,
    PATH_FRONTIERS_UPDATED,
    PATH_RESET,
    INTERACT,
    TILE_SELECTED,
    INTERACT_ENCOUNTER_ENEMY,
    CUTSCENE_ENCOUNTER_ENEMY_END,
    CUTSCENE_COMBAT_ACCEPT
}
