namespace Amegakure.Starkane.PubSub
{
    public enum GameEvent
    {
        CHARACTER_MOVE_START,
        CHARACTER_MOVE_END,
        PATH_FRONTIERS_RESET,
        TILE_SELECTED,
        INPUT_CHARACTER_SELECTED,
        INPUT_CHARACTER_UNSELECTED,
        INPUT_COMBAT_CHALLENGE,
        CUTSCENE_ENCOUNTER_ENEMY_END,
        INPUT_COMBAT_CANCEL,
        INPUT_COMBAT_ACCEPT,
        COMBAT_TURN_CHANGED,
        COMBAT_SKILL_DONE,
        FRONTIER_UPDATED,
        INPUT_CHARACTER_HOVER,
        INPUT_CHARACTER_UNHOVER,
        CUTSCENE_COMBAT_START,
        CUTSCENE_COMBAT_END,
        COMBAT_VICTORY,
        COMBAT_CHARACTER_DEAD,
        GAME_LOADING_START
    }
}