namespace Amegakure.Starkane.PubSub
{
    public enum GameEvent
    {
        CHARACTER_MOVE_START,
        CHARACTER_MOVE_END,
        PATH_FRONTIERS_RESET,
        TILE_SELECTED,
        INPUT_CHARACTER_SELECTED,
        INPUT_CHARACTER_UNSELECTED,
        INPUT_ENEMY_COMBAT_INTERACTION,
        CUTSCENE_ENCOUNTER_ENEMY_END,
        CUTSCENE_COMBAT_CANCEL,
        CUTSCENE_COMBAT_ACCEPT,
        COMBAT_TURN_CHANGED,
        COMBAT_SKILL_DONE,
        FRONTIER_UPDATED,
        INPUT_CHARACTER_HOVER,
        INPUT_CHARACTER_UNHOVER
    }
}